### ISSUE TITLE
apkupdade

### ISSUE THREAD

**Issue by a2240085278** [kelinZhou/ApkUpdater#2]
8.0以上在执行下载的时候 没有下载  直接结束

**Comment by kelinZhou** [comment]
是所有的8.0设备上吗？还是某个品牌的？我自己的8.0华为测试没问题啊。发自我的华为手机-------- 原始邮件 --------主题：[kelinZhou/ApkUpdater] apkupdade (#2)发件人：a2240085278 收件人：kelinZhou/ApkUpdater 抄送：Subscribed 8.0以上在执行下载的时候 没有下载  直接结束



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/kelinZhou/ApkUpdater/issues/2?email_source=notifications\u0026email_token=AESCWGKB7N4VWATSYIYRZR3PYDR7VA5CNFSM4HRWSUWKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4GW473WQ",

"url": "https://github.com/kelinZhou/ApkUpdater/issues/2?email_source=notifications\u0026email_token=AESCWGKB7N4VWATSYIYRZR3PYDR7VA5CNFSM4HRWSUWKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4GW473WQ",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by kelinZhou** [comment]
你的问题已经解决，是在抱歉前段时间比较忙，一直没有时间处理。这个问题是8.0的动态权限导致的。如果你的targetVersion小于26就应该不会出现这个问题。
不过该问题已经在2.2.1版本解决。谢谢你的反馈。
