### ISSUE TITLE
你好，混淆后崩溃，需要怎么添加混淆规则

### ISSUE THREAD

**Issue by violetnight** [kelinZhou/ApkUpdater#4]

**Comment by kelinZhou** [comment]
返校之后崩溃是这个库的代码崩溃吗？如果是的话你直接把我包名下的所有类。都不要混淆。发自我的华为手机-------- 原始邮件 --------发件人： 紫小夜 ***@***.***>日期： 2021年8月20日周五 上午9:54收件人： kelinZhou/ApkUpdater ***@***.***>抄送： Subscribed ***@***.***>主    题： [kelinZhou/ApkUpdater] 你好，混淆后崩溃，需要怎么添加混淆规则 (#4)

**Comment by violetnight** [comment]
是的，下载完之后崩溃，我我试试取消混淆就正常了

**Comment by violetnight** [comment]
是你那边引入第三方库没处理混淆么，我这边试了模拟器下载完可以直接安装，真机跳转权限开启页面就会出现问题

**Comment by kelinZhou** [comment]
-keep class com.kelin.** {*;}
你加上上面这行,如果还有问题请加我微信：kelinZQL



在 2021-08-20 15:13:37，"紫小夜" ***@***.***> 写道：

是你那边引入第三方库没处理混淆么，我这边试了模拟器下载完可以直接安装，真机跳转权限开启页面就会出现问题

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by violetnight** [comment]
解决了，有个权限的包被混淆了，谢谢

**Comment by kelinZhou** [comment]
是OkPermission吗？因为这个也是我的库。如果要试的话我要去看一下是什么原因。发自我的华为手机-------- 原始邮件 --------发件人： 紫小夜 ***@***.***>日期： 2021年8月20日周五 下午3:43收件人： kelinZhou/ApkUpdater ***@***.***>抄送： Kelin ***@***.***>, Comment ***@***.***>主    题： Re: [kelinZhou/ApkUpdater] 你好，混淆后崩溃，需要怎么添加混淆规则 (#4)

解决了，有个权限的包被混淆了，谢谢
